Group tool templating exceptions in sentry
This will properly group tool templating exceptions.
The added tags should make it easy to prioritize and distribute fixes.
Also improves the exception if not using sentry:
```
...
Cheetah.Parser.ParseError:

Some #directives are missing their corresponding #end ___ tag: for
Line 3, column 4

Line|Cheetah Code
----|-------------------------------------------------------------
2   |        moo
3   |
        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/runners/__init__.py", line 297, in prepare_job
    job_wrapper.prepare()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/__init__.py", line 1260, in prepare
    ) = tool_evaluator.build()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/evaluation.py", line 611, in build
    global_tool_logs(self._build_command_line, config_file, "Building Command Line", self.tool)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/evaluation.py", line 111, in global_tool_logs
    raise ToolTemplatingException(
galaxy.tools.evaluation.ToolTemplatingException: Error occurred while building command line for tool 'cheetah_problem_syntax_error'
```